/**
 * backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Backend) {
      root.Backend = {};
    }
    root.Backend.Article = factory(root.Backend.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Article model module.
   * @module model/Article
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Article</code>.
   * @alias module:model/Article
   * @class
   * @param feedId {Number} 
   */
  var exports = function(feedId) {
    var _this = this;






    _this['feedId'] = feedId;


  };

  /**
   * Constructs a <code>Article</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Article} obj Optional instance to populate.
   * @return {module:model/Article} The populated <code>Article</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('publishedVersion')) {
        obj['publishedVersion'] = ApiClient.convertToType(data['publishedVersion'], 'Number');
      }
      if (data.hasOwnProperty('publishedAt')) {
        obj['publishedAt'] = ApiClient.convertToType(data['publishedAt'], 'Date');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
      }
      if (data.hasOwnProperty('updatedAt')) {
        obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
      }
      if (data.hasOwnProperty('isDeleted')) {
        obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
      }
      if (data.hasOwnProperty('feedId')) {
        obj['feedId'] = ApiClient.convertToType(data['feedId'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('articleId')) {
        obj['articleId'] = ApiClient.convertToType(data['articleId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} publishedVersion
   */
  exports.prototype['publishedVersion'] = undefined;
  /**
   * @member {Date} publishedAt
   */
  exports.prototype['publishedAt'] = undefined;
  /**
   * @member {Date} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {Date} updatedAt
   */
  exports.prototype['updatedAt'] = undefined;
  /**
   * @member {Boolean} isDeleted
   * @default false
   */
  exports.prototype['isDeleted'] = false;
  /**
   * @member {Number} feedId
   */
  exports.prototype['feedId'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} articleId
   */
  exports.prototype['articleId'] = undefined;



  return exports;
}));


