/**
 * backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Backend);
  }
}(this, function(expect, Backend) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Backend.ArticleApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArticleApi', function() {
    describe('articleCount', function() {
      it('should call articleCount successfully', function(done) {
        //uncomment below and update the code to test articleCount
        //instance.articleCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleCreate', function() {
      it('should call articleCreate successfully', function(done) {
        //uncomment below and update the code to test articleCreate
        //instance.articleCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleCreateChangeStreamGetArticlesChangeStream', function() {
      it('should call articleCreateChangeStreamGetArticlesChangeStream successfully', function(done) {
        //uncomment below and update the code to test articleCreateChangeStreamGetArticlesChangeStream
        //instance.articleCreateChangeStreamGetArticlesChangeStream(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleCreateChangeStreamPostArticlesChangeStream', function() {
      it('should call articleCreateChangeStreamPostArticlesChangeStream successfully', function(done) {
        //uncomment below and update the code to test articleCreateChangeStreamPostArticlesChangeStream
        //instance.articleCreateChangeStreamPostArticlesChangeStream(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleDeleteById', function() {
      it('should call articleDeleteById successfully', function(done) {
        //uncomment below and update the code to test articleDeleteById
        //instance.articleDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleExistsGetArticlesidExists', function() {
      it('should call articleExistsGetArticlesidExists successfully', function(done) {
        //uncomment below and update the code to test articleExistsGetArticlesidExists
        //instance.articleExistsGetArticlesidExists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleExistsHeadArticlesid', function() {
      it('should call articleExistsHeadArticlesid successfully', function(done) {
        //uncomment below and update the code to test articleExistsHeadArticlesid
        //instance.articleExistsHeadArticlesid(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleFind', function() {
      it('should call articleFind successfully', function(done) {
        //uncomment below and update the code to test articleFind
        //instance.articleFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleFindById', function() {
      it('should call articleFindById successfully', function(done) {
        //uncomment below and update the code to test articleFindById
        //instance.articleFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleFindOne', function() {
      it('should call articleFindOne successfully', function(done) {
        //uncomment below and update the code to test articleFindOne
        //instance.articleFindOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articlePatchOrCreate', function() {
      it('should call articlePatchOrCreate successfully', function(done) {
        //uncomment below and update the code to test articlePatchOrCreate
        //instance.articlePatchOrCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articlePrototypeGetFeed', function() {
      it('should call articlePrototypeGetFeed successfully', function(done) {
        //uncomment below and update the code to test articlePrototypeGetFeed
        //instance.articlePrototypeGetFeed(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articlePrototypePatchAttributes', function() {
      it('should call articlePrototypePatchAttributes successfully', function(done) {
        //uncomment below and update the code to test articlePrototypePatchAttributes
        //instance.articlePrototypePatchAttributes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleReplaceByIdPostArticlesidReplace', function() {
      it('should call articleReplaceByIdPostArticlesidReplace successfully', function(done) {
        //uncomment below and update the code to test articleReplaceByIdPostArticlesidReplace
        //instance.articleReplaceByIdPostArticlesidReplace(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleReplaceByIdPutArticlesid', function() {
      it('should call articleReplaceByIdPutArticlesid successfully', function(done) {
        //uncomment below and update the code to test articleReplaceByIdPutArticlesid
        //instance.articleReplaceByIdPutArticlesid(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleReplaceOrCreatePostArticlesReplaceOrCreate', function() {
      it('should call articleReplaceOrCreatePostArticlesReplaceOrCreate successfully', function(done) {
        //uncomment below and update the code to test articleReplaceOrCreatePostArticlesReplaceOrCreate
        //instance.articleReplaceOrCreatePostArticlesReplaceOrCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleReplaceOrCreatePutArticles', function() {
      it('should call articleReplaceOrCreatePutArticles successfully', function(done) {
        //uncomment below and update the code to test articleReplaceOrCreatePutArticles
        //instance.articleReplaceOrCreatePutArticles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleUpdateAll', function() {
      it('should call articleUpdateAll successfully', function(done) {
        //uncomment below and update the code to test articleUpdateAll
        //instance.articleUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('articleUpsertWithWhere', function() {
      it('should call articleUpsertWithWhere successfully', function(done) {
        //uncomment below and update the code to test articleUpsertWithWhere
        //instance.articleUpsertWithWhere(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
